const cartTypes = {
    TOGGLE_DROPDOWN:'TOGGLE_DROPDOWN',
    ALL_ITEMS:'ALL_ITEMS',
    REMOVE_ITEMS:'REMOVE_ITEMS',
    REMOV_LEFT:'REMOVE_LEFT',
    CLEAR_CART:'CLEAR_CART'
}

export default cartTypes;