export const usertypes = {
    SIGNIN_GOOGLE_START:'SIGNIN_GOOGLE_START',
    EMAIL_GOOGLE_START:'EMAIL_GOOGLE_START',
    SIGNIN_SUCCESS:'SIGNIN_SUCCESS',
    SIGNIN_FAIL:'SIGNIN_FAIL',
    SIGNUP_START:'SIGNUP_START',
    SIGNUP_SUCCESSFUL:'SIGNUP_SUCCESSFUL',
    SIGNUP_FAIL:'SIGNUP_FAIL',
    CHECK_USER_SESSION:'CHECK_USER_SESSION',
    SIGN_OUT_SESSION:'SIGN_OUT_SESSION',
    SIGN_OUT_SUCCESSFUL:'SIGN_OUT_SUCCESSFUL',
    SIGN_OUT_FAILURE:'SIGN_OUT_FAILURE'
    
}